agsistemas/agsistemas/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('app_agsistemas.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

agsistemas/app_agsistemas/urls.py
from django.urls import path
from .views import (PaginaInicialView, VeiculosView, CriarVeiculoView,
                    EditarVeiculoView, ExcluirVeiculoView, MotoristasView, CriarMotoristaView,
                     ExcluirMotoristaView, EditarMotoristaView, MotoristaDetailView, ControleCreateView, VeiculoDetailView, ControleDeleteView, ControleDetailView, ControleUpdateView, ControleListView)

urlpatterns = [
    path('', PaginaInicialView.as_view(), name='pagina_inicial'),
    path('veiculos/', VeiculosView.as_view(), name='veiculos'),
    path('veiculos/criar/', CriarVeiculoView.as_view(), name='criar_veiculo'),
    path('veiculos/<int:veiculo_id>/editar/', EditarVeiculoView.as_view(), name='editar_veiculo'),
    path('veiculos/<int:veiculo_id>/excluir/', ExcluirVeiculoView.as_view(), name='excluir_veiculo'),
    path('veiculos/<int:pk>/', VeiculoDetailView.as_view(), name='veiculo_detail'),
    path('motoristas/', MotoristasView.as_view(), name='motoristas'),
    path('motoristas/criar/', CriarMotoristaView.as_view(), name='criar_motorista'),
    path('motoristas/<int:motorista_id>/excluir/', ExcluirMotoristaView.as_view(), name='excluir_motorista'),
    path('motoristas/<int:motorista_id>/editar/', EditarMotoristaView.as_view(), name='editar_motorista'),
    path('motoristas/<int:pk>/', MotoristaDetailView.as_view(), name='motorista_detail'),
    path('controle/', ControleListView.as_view(), name='controle_list'),
    path('controle/<int:pk>/', ControleDetailView.as_view(), name='controle_detail'),
    path('controle/create/', ControleCreateView.as_view(), name='controle_create'),
    path('controle/<int:pk>/update/', ControleUpdateView.as_view(), name='controle_update'),
    path('controle/<int:pk>/delete/', ControleDeleteView.as_view(), name='controle_delete'),
]

agsistemas/app_agsistemas/models.py
from django.db import models

class Veiculo(models.Model):
    placa = models.CharField(max_length=20)
    marca = models.CharField(max_length=100)
    modelo = models.CharField(max_length=100)
    km_troca_oleo = models.PositiveIntegerField()

    def save(self, *args, **kwargs):
        self.placa = self.placa.upper()
        self.marca = self.marca.upper()
        self.modelo = self.modelo.upper()
        super().save(*args, **kwargs)

    def __str__(self):
        return self.placa

class Motorista(models.Model):
    cod_motorista = models.AutoField(primary_key=True)
    nome = models.CharField(max_length=100)
    telefone = models.CharField(max_length=20)
    cnh = models.CharField(max_length=20)

    def save(self, *args, **kwargs):
        self.nome = self.nome.upper()
        super().save(*args, **kwargs)

    def __str__(self):
        return self.nome

class Controle(models.Model):
    veiculo = models.ForeignKey(Veiculo, on_delete=models.CASCADE)
    motorista = models.ForeignKey(Motorista, on_delete=models.CASCADE)
    data_saida = models.DateField()
    hora_saida = models.TimeField()
    km_saida = models.PositiveIntegerField()
    destino = models.CharField(max_length=200)
    data_retorno = models.DateField(null=True, blank=True)
    hora_retorno = models.TimeField(null=True, blank=True)
    km_retorno = models.PositiveIntegerField(null=True, blank=True)
    km_percorrido = models.PositiveIntegerField(null=True, blank=True)

    def save(self, *args, **kwargs):
        self.destino = self.destino.upper()
        super().save(*args, **kwargs)

    def __str__(self):
        return f"Controle de {self.veiculo} - {self.data_saida}"

agsistemas/app_agsistemas/forms.py
from django import forms
from .models import Veiculo, Motorista, Controle
import re

class VeiculoForm(forms.ModelForm):

    class Meta:
        model = Veiculo
        fields = ['placa', 'marca', 'modelo', 'km_troca_oleo']
        labels = {
            'placa': 'Placa do Veículo',
            'marca': 'Marca do Veículo',
            'modelo': 'Modelo do Veículo',
            'km_troca_oleo': 'KM para Próxima Troca de Óleo',
        }
        widgets = {
            'km_troca_oleo': forms.NumberInput(attrs={'min': 0}),
        }

    def clean(self):
        cleaned_data = super().clean()
        placa = cleaned_data.get('placa')
        telefone = cleaned_data.get('telefone')

        pattern = re.compile(r'^([A-Z]{3}-\d{4}|[A-Z]{3}\d{1}[A-Z]\d{2})$')
        if not pattern.match(placa):
            raise forms.ValidationError("A placa do veículo não está em um formato válido.")
        if Veiculo.objects.filter(placa=placa).exists():
            raise forms.ValidationError("Veiculo com a placa ja adicionada anteriormente.")

        return cleaned_data


class MotoristaForm(forms.ModelForm):
    class Meta:
        model = Motorista
        fields = ['nome', 'telefone', 'cnh']
        labels = {
            'nome': 'Nome do Motorista',
            'telefone': 'Telefone do Motorista',
            'cnh': 'CNH do Motorista',
        }
        widgets = {
            'telefone': forms.TextInput(attrs={'placeholder': 'Ex: (99) 99999-9999'}),
        }

    def clean(self):
        cleaned_data = super().clean()
        cnh = cleaned_data.get('cnh')
        telefone = cleaned_data.get('telefone')

        if len(cnh) != 9 or not cnh.isdigit():
            raise forms.ValidationError("A CNH deve ter exatamente 9 caracteres numéricos.")
        if len(telefone) != 11 or not telefone.isdigit():
            raise forms.ValidationError("O número de telefone deve ter exatamente 11 caracteres numéricos.")

        if Motorista.objects.filter(cnh=cnh).exists():
            raise forms.ValidationError("Já existe um motorista cadastrado com este CNH.")
        if Motorista.objects.filter(telefone=telefone).exists():
            raise forms.ValidationError("Telefone já cadastrado.")

        return cleaned_data


class ControleForm(forms.ModelForm):
    class Meta:
        model = Controle
        fields = ['veiculo', 'motorista', 'data_saida', 'hora_saida', 'km_saida', 'destino', 'data_retorno', 'hora_retorno', 'km_retorno', 'km_percorrido']
        widgets = {
            'data_saida': forms.DateInput(attrs={'type': 'date'}),
            'hora_saida': forms.TimeInput(attrs={'type': 'time'}),
            'data_retorno': forms.DateInput(attrs={'type': 'date'}),
            'hora_retorno': forms.TimeInput(attrs={'type': 'time'}),
            'veiculo': forms.Select(),
            'motorista': forms.Select(),
        }
    def clean(self):
        cleaned_data = super().clean()
        data_saida = cleaned_data.get("data_saida")
        hora_saida = cleaned_data.get("hora_saida")
        data_retorno = cleaned_data.get("data_retorno")
        hora_retorno = cleaned_data.get("hora_retorno")
        km_saida = cleaned_data.get("km_saida")
        km_retorno = cleaned_data.get("km_retorno")

        if data_saida and data_retorno and data_retorno < data_saida:
            raise forms.ValidationError("A data de retorno não pode ser anterior à data de saída.")

        if data_saida == data_retorno and hora_saida and hora_retorno and hora_retorno < hora_saida:
            raise forms.ValidationError("A hora de retorno não pode ser anterior à hora de saída se ambas as datas forem iguais.")

        if km_saida is not None and km_retorno is not None:
            cleaned_data['km_percorrido'] = km_retorno - km_saida
        else:
            cleaned_data['km_percorrido'] = None

        return cleaned_data

agsistemas/app_agsistemas/views.py
from django.views import View
from django.shortcuts import render, redirect
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, DetailView
from django.urls import reverse_lazy
from .models import Veiculo, Motorista, Controle
from .forms import VeiculoForm, MotoristaForm, ControleForm

class PaginaInicialView(View):
    def get(self, request):
        veiculos_count = Veiculo.objects.count()
        motoristas_count = Motorista.objects.count()
        return render(request, 'pagina_inicial.html', {'veiculos_count': veiculos_count, 'motoristas_count': motoristas_count})



#Controle
class ControleListView(ListView):
    model = Controle
    template_name = 'controle_list.html'
    context_object_name = 'controles'
    ordering = ['-data_saida']


class ControleCreateView(CreateView):
    model = Controle
    form_class = ControleForm
    template_name = 'controle_form.html'
    success_url = reverse_lazy('controle_list')


class ControleUpdateView(UpdateView):
    model = Controle
    form_class = ControleForm
    template_name = 'controle_form.html'
    success_url = reverse_lazy('controle_list')


class ControleDeleteView(DeleteView):
    model = Controle
    template_name = 'controle_confirm_delete.html'
    success_url = reverse_lazy('controle_list')


class ControleDetailView(DetailView):
    model = Controle
    template_name = 'controle_detail.html'
    context_object_name = 'controle'



#veiculos
class VeiculosView(View):
    def get(self, request):
        veiculos = Veiculo.objects.all()
        return render(request, 'veiculos.html', {'veiculos': veiculos})


class CriarVeiculoView(View):
    def get(self, request):
        form = VeiculoForm()
        return render(request, 'criar_veiculo.html', {'form': form, 'mensagem_aviso': None})

    def post(self, request):
        form = VeiculoForm(request.POST)
        if form.is_valid():
            placa = form.cleaned_data['placa']
            if not Veiculo.objects.filter(placa=placa).exists():
                form.save()
                return redirect('pagina_inicial')
            else:
                mensagem_aviso = 'Placa já cadastrada.'
                return render(request, 'criar_veiculo.html', {'form': form, 'mensagem_aviso': mensagem_aviso})

        return render(request, 'criar_veiculo.html', {'form': form, 'mensagem_aviso': None})


class EditarVeiculoView(View):
    def get(self, request, veiculo_id):
        veiculo = Veiculo.objects.get(pk=veiculo_id)
        form = VeiculoForm(instance=veiculo)
        return render(request, 'editar_veiculo.html', {'form': form})

    def post(self, request, veiculo_id):
        veiculo = Veiculo.objects.get(pk=veiculo_id)
        form = VeiculoForm(request.POST, instance=veiculo)
        if form.is_valid():
            form.save()
            return redirect('veiculos')
        return render(request, 'editar_veiculo.html', {'form': form})


class ExcluirVeiculoView(View):
    def get(self, request, veiculo_id):
        veiculo = Veiculo.objects.get(pk=veiculo_id)
        return render(request, 'excluir_veiculo.html', {'veiculo': veiculo})

    def post(self, request, veiculo_id):
        veiculo = Veiculo.objects.get(pk=veiculo_id)
        veiculo.delete()
        return redirect('veiculos')


class VeiculoDetailView(DetailView):
    model = Veiculo
    template_name = 'veiculo_detail.html'
    context_object_name = 'veiculo'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        veiculo = self.get_object()

        controles = Controle.objects.filter(veiculo=veiculo)

        motoristas_datas = []

        for controle in controles:
            motoristas_datas.append((controle.motorista.nome, controle.data_saida, controle.data_retorno))

        context['motoristas_datas'] = motoristas_datas

        return context



#motoristas
class MotoristasView(View):
    def get(self, request):
        motoristas = Motorista.objects.all()
        return render(request, 'motoristas.html', {'motoristas': motoristas})


class CriarMotoristaView(View):
    def get(self, request):
        form = MotoristaForm()
        return render(request, 'criar_motorista.html', {'form': form, 'mensagem_aviso': None})

    def post(self, request):
        form = MotoristaForm(request.POST)
        if form.is_valid():
            cnh = form.cleaned_data['cnh']
            telefone = form.cleaned_data['telefone']
            if not Motorista.objects.filter(cnh=cnh).exists() and not Motorista.objects.filter(telefone=telefone).exists():
                form.save()
                return redirect('pagina_inicial')
            elif Motorista.objects.filter(cnh=cnh).exists():
                mensagem_aviso = 'CNH já cadastrada.'
            else:
                mensagem_aviso = 'Telefone já cadastrado.'
            return render(request, 'criar_motorista.html', {'form': form, 'mensagem_aviso': mensagem_aviso})
        return render(request, 'criar_motorista.html', {'form': form, 'mensagem_aviso': None})


class ExcluirMotoristaView(View):
    def get(self, request, motorista_id):
        motorista = Motorista.objects.get(pk=motorista_id)
        return render(request, 'excluir_motorista.html', {'motorista': motorista})

    def post(self, request, motorista_id):
        motorista = Motorista.objects.get(pk=motorista_id)
        motorista.delete()
        return redirect('motoristas')


class EditarMotoristaView(View):
    def get(self, request, motorista_id):
        motorista = Motorista.objects.get(pk=motorista_id)
        form = MotoristaForm(instance=motorista)
        return render(request, 'editar_motorista.html', {'form': form, 'motorista': motorista})

    def post(self, request, motorista_id):
        motorista = Motorista.objects.get(pk=motorista_id)
        form = MotoristaForm(request.POST, instance=motorista)
        if form.is_valid():
            form.save()
            return redirect('motoristas')
        return render(request, 'editar_motorista.html', {'form': form, 'motorista': motorista})


class MotoristaDetailView(DetailView):
    model = Motorista
    template_name = 'motorista_detail.html'
    context_object_name = 'motorista'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        motorista = self.get_object()

        controles = Controle.objects.filter(motorista=motorista)

        if controles:
            context['controles'] = controles

        return context

agsistemas/app_agsistemas/templates/controle_confirm_delete.html
{% extends 'base.html' %}

{% block title %}
    Confirmar Exclusão do Controle de Veículo
{% endblock %}

{% block content %}

<style>
    .custom-h1 {
        font-size: 2rem;
    }

    .custom-label {
        font-size: 1.1rem;
    }

    /* Adicionando margem superior para os botões */
    .btn {
        margin-top: 20px;
    }
</style>

<div class="container mt-5 pt-5">
    <h1 class="text-center custom-h1 pt-12 mt-12 ml-12"> Confirmar Exclusão do Controle de Veículo</h1>
    <p class="text-center custom-label mt-5 ml-8">Você está prestes a excluir o registro de controle de veículo. Tem certeza que deseja continuar?</p>
    <form method="post" class="text-center">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger custom-label">Confirmar</button>
        <a href="{% url 'controle_list' %}" class="btn btn-primary custom-label ml-12">Cancelar</a>
    </form>
</div>
{% endblock %}

agsistemas/app_agsistemas/templates/controle_detail.html
{% extends 'base.html' %}

{% block title %}
    Detalhes do Controle de Veículos
{% endblock %}

{% block content %}

    <style>
        .custom-h1 {
            font-size: 2rem;
        }

        .custom-label {
            font-size: 1.1rem;
        }

    </style>

     <div class="container mt-5 pt-3">
    <h1 class="text-center custom-h1 pt-12 mt-12 ml-12">Detalhes do Controle de Veículo</h1>
    <dl class="row">
        <div class="table-responsive p-3 ml-9 ">

        <dt class="col-sm-3">Motorista:</dt>
        <dd class="col-sm-9">{{ controle.motorista }}</dd>

        <dt class="col-sm-3">Veículo:</dt>
        <dd class="col-sm-9">{{ controle.veiculo }}</dd>

        <dt class="col-sm-3">Data Saída:</dt>
        <dd class="col-sm-9">{{ controle.data_saida }}</dd>

        <dt class="col-sm-3">Horario da Saída:</dt>
        <dd class="col-sm-9">{{ controle.hora_saida }}</dd>

        <dt class="col-sm-3">KM Saída:</dt>
        <dd class="col-sm-9">{{ controle.km_saida }}</dd>

        <dt class="col-sm-3">Destino:</dt>
        <dd class="col-sm-9">{{ controle.destino }}</dd>

        <dt class="col-sm-3">Data do Retorno:</dt>
        <dd class="col-sm-9">{{ controle.data_retorno }}</dd>

        <dt class="col-sm-3">Hora do Retorno:</dt>
        <dd class="col-sm-9">{{ controle.hora_retorno }}</dd>

        <dt class="col-sm-3">KM Retorno:</dt>
        <dd class="col-sm-9">{{ controle.km_retorno }}</dd>

        <dt class="col-sm-3">KM Percorrido:</dt>
        <dd class="col-sm-9">{{ controle.km_percorrido }}</dd>

    </dl>
    <a href="{% url 'controle_list' %}" class="btn btn-secondary ml-9">Voltar</a>
{% endblock %}

agsistemas/app_agsistemas/templates/controle_form.html
{% extends 'base.html' %}

{% block title %}
    {% if form.instance.pk %}
        Editar Controle de Veículo
    {% else %}
        Adicionar Controle de Veículo
    {% endif %}
{% endblock %}

{% block content %}

    <style>
        .custom-h1 {
            font-size: 2rem;
        }

        .custom-label {
            font-size: 1.1rem;
        }

    </style>
    <div class="container pt-5">
        <h1 class="text-center custom-h1 pt-8 mt-4 ml-12">{% if form.instance.pk %}Editar Controle de Veículo{% else %}Controle de Veículo{% endif %}</h1>

        <form method="post" class="row">
        {% csrf_token %}
            <div class="col-md-6 offset-md-3">
            {% if form.non_field_errors %}
            <div class="alert alert-danger mt-1 text-center" role="alert">
                <ul>
                    {% for error in form.non_field_errors %}
                    <li>{{ error }}</li>
                    {% endfor %}
                </ul>
            </div>
            {% endif %}

    <div class="mt-1 mb-3">
    <label for="id_veiculo" class="col-md-2 col-form-label">Placa</label>
    <select name="veiculo" id="id_veiculo" class="form-select">
        {% for veiculo in form.veiculo.field.queryset %}
            <option value="{{ veiculo.pk }}">{{ veiculo.nome }} - {{ veiculo.placa }}</option>
        {% endfor %}

                {% if form.errors.veiculo %}
                    {% for error in form.errors.veiculo %}
                        <div class="invalid-feedback d-block">{{ error }}</div>
                    {% endfor %}
                {% endif %}
    </select>
</div>

            <div class="mb-3">
                <label for="id_motorista" class="form-label">Motorista</label>
                    <select name="motorista" id="id_motorista" class="form-select">

        {% for motorista in form.motorista.field.queryset %}
            <option value="{{ motorista.pk }}">{{ motorista.nome }}</option>
        {% endfor %}
                {% if form.errors.motorista %}
                    {% for error in form.errors.motorista %}
                        <div class="invalid-feedback d-block">{{ error }}</div>
                    {% endfor %}
                {% endif %}

    </select>
</div>

            <div class="mb-3">
                <label for="id_data_saida" class="form-label mr-4">Data de Saída</label>
                {{ form.data_saida }}
            </div>

            <div class="mb-3">
                <label for="id_hora_saida" class="form-label mr-4">Hora de Saída</label>
                {{ form.hora_saida }}
            </div>

            <div class="mb-3">
                <label for="id_km_saida" class="form-label mr-4">Km de Saída</label>
                {{ form.km_saida }}
            </div>

            <div class="mb-3">
                <label for="id_destino" class="form-label mr-4">Destino</label>
                {{ form.destino }}
            </div>

            <div class="mb-3">
                <label for="id_data_retorno" class="form-label mr-4">Data de Retorno</label>
                {{ form.data_retorno }}
            </div>

            <div class="mb-3">
                <label for="id_hora_retorno" class="form-label mr-4">Hora de Retorno</label>
                {{ form.hora_retorno }}
            </div>

            <div class="mb-3">
                <label for="id_km_retorno" class="form-label mr-4">Km de Retorno</label>
                {{ form.km_retorno }}
            </div>

            <a href="{% url 'controle_list' %}" class="btn btn-secondary ml-7">Cancelar</a>
            <button type="submit" class="btn btn-primary ml-8">Salvar</button>

        </form>
    </div>
{% endblock %}

agsistemas/app_agsistemas/templates/criar_veiculo.html
{% extends 'base.html' %}

{% block title %}
    Adicionar Veiculo
{% endblock %}

{% block content %}
    <style>
        .custom-h1 {
            font-size: 2rem;
        }

        .custom-label {
            font-size: 1.1rem;
        }

    </style>


    <div class="container mt-5 pt-5">
    <h1 class="text-center custom-h1 pt-12 mt-12 ml-12">Adicionar Veiculo</h1>
    <form method="post" class="row">
        {% csrf_token %}
        <div class="col-md-6 offset-md-3">
            {% if form.non_field_errors %}
            <div class="alert alert-danger mt-4 text-center" role="alert">
                <ul>
                    {% for error in form.non_field_errors %}
                    <li>{{ error }}</li>
                    {% endfor %}
                </ul>
            </div>
            {% endif %}

            <div class="row mt-8 mb-6 text-center align-items-center">
                <label for="id_placa" class="col-md-6 col-form-label text-md-end custom-label">Placa</label>
                <div class="col-md-1">
                    {{ form.placa }}
                </div>
            </div>
            <div class="row mb-6 text-center align-items-center">
                <label for="id_marca" class="col-md-6 col-form-label text-md-end custom-label">Marca</label>
                <div class="col-md-1">
                    {{ form.marca }}
                </div>
            </div>
            <div class="row mb-6 text-center align-items-center">
                <label for="id_modelo" class="col-md-6 col-form-label text-md-end custom-label">Modelo</label>
                <div class="col-md-1">
                    {{ form.modelo }}
                </div>
            </div>
            <div class="row mb-6 text-center align-items-center">
                <label for="id_km_troca_oleo" class="col-md-6 col-form-label text-md-end custom-label">Km para Troca de Óleo</label>
                <div class="col-md-1">
                    {{ form.km_troca_oleo }}
                </div>
            </div>
            <div class="row">
                <div class="col-md-12 text-center">
                    <button type="submit" class="btn btn-primary">Adicionar Veiculo</button>
                </div>
            </div>
        </div>
    </form>
</div>

{% endblock %}

agsistemas/app_agsistemas/templates/editar_motorista.html
{% extends 'base.html' %}

{% block title %}
    Editar Motorista
{% endblock %}

{% block content %}
    <style>
        .custom-h1 {
            font-size: 2rem;
        }

        .custom-label {
            font-size: 1.1rem;
        }
    </style>


 <div class="container mt-5 pt-5">
    <h1 class="text-center custom-h1 pt-12 mt-12 ml-12">Editar Motorista</h1>
        <form method="post" class="row">
            {% csrf_token %}
            <div class="col-md-6 offset-md-3">
                {% if form.non_field_errors %}
                    <div class="alert alert-danger" role="alert">
                        <ul>
                            {% for error in form.non_field_errors %}
                                <li>{{ error }}</li>
                            {% endfor %}
                        </ul>
                    </div>
                {% endif %}
                <div class="row mt-8 mb-6 text-center align-items-center">
                    <label for="id_nome" class="col-md-6 col-form-label text-md-end custom-label">Nome completo</label>
                    <div class="col-md-1">
                        {{ form.nome }}
                    </div>
                </div>
                <div class="row mt-8 mb-6 text-center align-items-center">
                    <label for="id_telefone" class="col-md-6 col-form-label text-md-end custom-label">Telefone / Celularo</label>
                    <div class="col-md-1">
                        {{ form.telefone }}
                    </div>
                </div>
                <div class="row mt-8 mb-6 text-center align-items-center">
                    <label for="id_cnh" class="col-md-6 col-form-label text-md-end custom-label">CNH</label>
                    <div class="col-md-1">
                        {{ form.cnh }}
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12 text-center">
                        <button type="submit" class="btn btn-primary">Salvar Alterações</button>
                    </div>
                </div>
            </div>
        </form>
    </div>
{% endblock %}

agsistemas/app_agsistemas/templates/editar_veiculo.html
{% extends 'base.html' %}

{% block title %}
    Editar Veículo
{% endblock %}

{% block content %}
 <style>
        .custom-h1 {
            font-size: 2rem;
        }

        .custom-label {
            font-size: 1.1rem;
        }

    </style>


     <div class="container mt-5 pt-5">
    <h1 class="text-center custom-h1 pt-12 mt-12 ml-12">Editar Veículo</h1>
        {% if form.non_field_errors %}
            <div class="alert alert-danger" role="alert">
                <ul>
                    {% for error in form.non_field_errors %}
                        <li>{{ error }}</li>
                    {% endfor %}
                </ul>
            </div>
        {% endif %}
    </div>

    <div class="container">
        <form method="post" class="row">
            {% csrf_token %}
            <div class="col-md-6 offset-md-3">
                <div class="row mb-3 align-items-center mt-4">
                    <label for="id_placa" class="col-md-6 col-form-label text-md-end custom-label">Placa</label>
                    <div class="col-md-6">
                        {{ form.placa }}
                        {% if form.placa.errors %}
                            <div class="alert alert-danger" role="alert">
                                <ul>
                                    {% for error in form.placa.errors %}
                                        <li>{{ error }}</li>
                                    {% endfor %}
                                </ul>
                            </div>
                        {% endif %}
                    </div>
                </div>
                <div class="row mb-3 align-items-center">
                    <label for="id_marca" class="col-md-6 col-form-label text-md-end custom-label">Marca</label>
                    <div class="col-md-6">
                        {{ form.marca }}
                    </div>
                </div>
                <div class="row mb-3 align-items-center">
                    <label for="id_modelo" class="col-md-6 col-form-label text-md-end custom-label">Modelo</label>
                    <div class="col-md-6">
                        {{ form.modelo }}
                    </div>
                </div>
                <div class="row mb-3 align-items-center">
                    <label for="id_km_troca_oleo" class="col-md-6 col-form-label text-md-end custom-label">Km para Troca de Óleo</label>
                    <div class="col-md-6">
                        {{ form.km_troca_oleo }}
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12 text-center">
                        <button type="submit" class="btn btn-primary">Salvar Alterações</button>
                    </div>
                </div>
            </div>
        </form>
    </div>
{% endblock %}

agsistemas/app_agsistemas/templates/excluir_motorista.html
{% extends 'base.html' %}

{% block title %}
    Confirmar Exclusão do Motorista
{% endblock %}

{% block content %}

<style>
    .custom-h1 {
        font-size: 2rem;
    }

    .custom-label {
        font-size: 1.1rem;
    }

    .btn {
        margin-top: 20px;
    }
</style>

<div class="container mt-5 pt-5">
    <h1 class="text-center custom-h1 pt-12 mt-12 ml-12"> Confirmar Exclusão do Motorista</h1>
    <p class="text-center custom-label mt-5 ml-8">Você está prestes a excluir o motorista do registro. Tem certeza que deseja continuar?</p>
    <form method="post" class="text-center">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger custom-label">Confirmar</button>
        <a href="{% url 'controle_list' %}" class="btn btn-primary custom-label ml-12">Cancelar</a>
    </form>
</div>
{% endblock %}